### ISSUE TITLE
只能本机访问

### ISSUE THREAD

**Issue by 0xbug** [AmyangXYZ/AssassinGo#2]
前端ajax.js 中
`const base = 'http://127.0.0.1:8000';`

![image](https://user-images.githubusercontent.com/12611275/40955923-e1178dd0-68bf-11e8-84a6-2f08cb789727.png)
![image](https://user-images.githubusercontent.com/12611275/40955996-5082d1d4-68c0-11e8-9331-8dd57a943396.png)

导致不能远程访问。
可否也把前端项目的源码也开源出来？

**Comment by AmyangXYZ** [comment]
前端也已开源 readme第一段 我给了链接

2018年6月5日 12:58，"0xbug" <notifications@github.com>写道：
