### ISSUE TITLE
搭建成功，进不了系统

### ISSUE THREAD

**Issue by r00tuser111** [AmyangXYZ/AssassinGo#3]
在centos下用docker搭建成功了，却发现进不去。抓包分析了一下。
感觉是硬编码的锅，请求发给了127.0.0.1:8000
![image](https://user-images.githubusercontent.com/22544959/41011927-caf3f27a-6971-11e8-9ceb-d40861829229.png)
bp改了一下包，发现也没办法进去。CROS的头也限制了只能接收localhost:8000
![image](https://user-images.githubusercontent.com/22544959/41011942-ddbb4b2e-6971-11e8-9bdd-a2391a5ddb3d.png)

麻烦大佬改一下了，谢谢。

**Comment by AmyangXYZ** [comment]
前端请求的base url指定的是127.0.0.1:8000，和后端监听端口一样，写好的docker-compose适用于在本地搭建的，如果想在vps上搭建请去clone[前端](https://github.com/U1in/AssassinGo-Front-End)然后改ajax和websocket的baseurl。改好重新打包前端然后将index.html和static/参考deploy.sh中的命令操作，让后端render即可。
那个CORS头是我们前后端交互开发时设置的，对部署没什么用，也没有删掉。
