### ISSUE TITLE
关于Honeypot Detect

### ISSUE THREAD

**Issue by d4wner** [AmyangXYZ/AssassinGo#4]
您好，很感兴趣您的Honeypot Detect模块是怎样实现的呢。
个人不太懂go，最近想跟一下这个模块的扩展，顺便想了解下您的检测思路呢？

**Comment by AmyangXYZ** [comment]
其实是调用的shodan的接口
https://honeyscore.shodan.io

2018年6月14日 10:02，"d4wner" <notifications@github.com>写道：
