### ISSUE TITLE
Error running AssassinGo

### ISSUE THREAD

**Issue by unstppbl** [AmyangXYZ/AssassinGo#5]
There was an error pulling chrome-headless, apparently the image doesn't exist anymore, so I pulled [this one](https://hub.docker.com/r/justinribeiro/chrome-headless/)
```bash
Pulling chromedp (knqz/chrome-headless:)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]y
Pulling chromedp (knqz/chrome-headless:)...
ERROR: pull access denied for knqz/chrome-headless, repository does not exist or may require 'docker login'
```
Then there was an error with `assassingo_mariadb_1` container
```bash
╰$ cat backup.sql | docker exec -i assassingo_mariadb_1 /usr/bin/mysql -uag --password=password ag
Error: No such container: assassingo_mariadb_1
```

**Comment by AmyangXYZ** [comment]
The chromedp package has updated his [docker](https://github.com/chromedp/examples/tree/master/standalone), I have updated my docker-compose.
And I can't reproduce mariadb error, did you modify the docker-compose.yml?

**Comment by unstppbl** [comment]
Nope, I didn't modify it. But after I pulled new docker-compose file it was okay.

Now, I run `cat backup.sql | docker exec -i assassingo_mariadb_1 /usr/bin/mysql -uag --password=password ag` command, and after try to login with admin:admin, but page isn't reacting, I'm pressing login and nothing happens..

**Comment by unstppbl** [comment]
![screenshot_2018-07-17_16-16-26](https://user-images.githubusercontent.com/13606833/42811589-ccd95d2e-89dc-11e8-9259-e4dd8c2ee252.png)
I guess this is the reason

**Comment by AmyangXYZ** [comment]
Oh, I pushed the server version on it.
Please use the last commit. I will fix it soon.

**Comment by AmyangXYZ** [comment]
I have fixed it, sorry for waiting so long
