### ISSUE TITLE
login issue

### ISSUE THREAD

**Issue by ghost** [AmyangXYZ/AssassinGo#6]
username:admin
password:admin
 it comes back saying wrong password or username 
![screenshot from 2018-07-27 21-21-14](https://user-images.githubusercontent.com/41809721/43351700-d3655f30-91e3-11e8-90d2-06e8ac6191ff.png)
![screenshot from 2018-07-27 21-21-30](https://user-images.githubusercontent.com/41809721/43351702-d9306a86-91e3-11e8-9dcb-411fa9ae7ef1.png)

**Comment by AmyangXYZ** [comment]
Did you restore the backup.sql? 
Go to the mariadb docker to see the username and password, or insert your own manually
```bash
# docker exec -it assassingo_mariadb_1 bash
# mysql -uag -ppassword
> use ag
> select * from users;
```
