### ISSUE TITLE
您好，项目前端部分的 项目地址无法访问

### ISSUE THREAD

**Issue by alex-marmot** [AmyangXYZ/AssassinGo#8]
您好，项目前端部分的 项目地址无法访问 https://github.com/U1in/AssassinGo-Front-End

**Comment by AmyangXYZ** [comment]
刚好我之前fork了一下 https://github.com/AmyangXYZ/AssassinGo-Front-End

**Comment by alex-marmot** [comment]
好的，谢谢分享。
